---
title: "Table 1 type Summary of Gila Monster Refuge Sites"
author: "CM Gienger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gt)
library(gtsummary)
library(Rmisc)
library(tidyverse)
library(flextable)
library(janitor)

data <- read_csv("../data/shelter_attributes.csv")
```

```{r look at data structure}
glimpse(data)
#wow, there are some problems with variable names.
```

```{r clean variable names}
data <- data %>% clean_names() %>% #makes variable have consistent formatting and pretty
  glimpse()
```

```{r select and format variables}
data_summary2 <- data %>% 
  dplyr::select(treatment, height, width, depth, roof, floor, logger_depth) %>%
  mutate(
    roof = as.numeric(roof),
    floor = as.numeric(floor),
    logger_depth = as.numeric(logger_depth)) 

#grouping variable and measurement variables
```

```{r make summary table with gtsummary, message=FALSE, warning=FALSE}
#Use the type = argument to override gtsummary’s automatic classification. In this case
#it took several attempts to force roof and floor variables to be numeric. 

table1 <- data_summary2 %>%
  tbl_summary(
    by = treatment,
    type = list(roof ~ "continuous", floor ~ "continuous"),
    statistic = all_continuous() ~ "{mean} ({sd})",
    digits = all_continuous() ~ 1,
    label = list(
      width ~ "Width (cm)",
      height ~ "Height (cm)",
      depth ~ "Depth (cm)",
      roof ~ "Roof",
      floor ~ "Floor",
      logger_depth ~ "Logger Depth (cm)"
    ),
    missing_text = "(Missing)"
  ) %>%
  add_p(test = everything() ~ "oneway.test")

table1
```


```{r show current values of the header, message=FALSE, warning=FALSE}
show_header_names(table1)
```

```{r modify table}
#remove sample size report (N) and superscripts
table1 <- table1 %>%
  modify_header(label = '**Attribute**',
  stat_1 = '**Actual**',
  stat_2 = '**Potential**',
  stat_3 = '**Random**',
  p.value = '**p-value**') %>%
  modify_footnote(everything() ~ NA) #gets rid of superscripts and footnotes; put them in table caption instead.
  
table1

#now you have a very clean table; most journals do not permit superscripts in tables.
#Can put details of statistical tests in Table caption
#after exporting to word processing program.

#post-hoc comparisons among groups are not easily supported currently in gtsummary (although technically possible); https://www.danieldsjoberg.com/gtsummary/reference/add_difference_row.tbl_summary.html
```

```{r export table to docx}
#table1 %>% 
  #as_gt() %>%
  #gt::gtsave("Figs/tab_1.docx")
##cannot open the .docx document; corrupted?
## maybe not supported: https://www.danieldsjoberg.com/gtsummary/articles/rmarkdown.html
```

```{r export table to rtf}
#table1 %>% 
  #as_gt() %>%
  #gt::gtsave("figs/tab_1.rtf")
##works but ugly as sin
```

```{r export table to docx via flextable}
table1 %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = "../figs/table1_flextable.docx")
```


